### ISSUE TITLE
mordor launch tracker

### ISSUE THREAD

**Issue by soc1c** [eth-classic/mordor#1]
### before launch

- [x] chain spec for parity
- [x] chain config for geth classic
- [x] genesis for multi-geth
- [x] prepare three bootnodes

### at launch
 
- [x] update timestamp
- [x] update extradata
- [x] launch bootnodes

### after launch

- [x] announce testnet
- [ ] write ecip to replace morden
- [x] deprecate morden
- [x] update clients
- [x] profit

**Comment by soc1c** [comment]
looks like parity no longer works

https://github.com/paritytech/parity-ethereum/issues/11119

**Comment by soc1c** [comment]
https://www.youtube.com/watch?v=Msi6EItbslk&start=24051
