### ISSUE TITLE
client integration tracker

### ISSUE THREAD

**Issue by soc1c** [eth-classic/mordor#3]
tracking client integration 

- [x] parity ethereum https://github.com/paritytech/parity-ethereum/pull/11200
- [x] multi-geth https://github.com/etclabscore/multi-geth/pull/38 https://github.com/multi-geth/multi-geth/pull/117
- [x] geth classic https://github.com/etclabscore/go-ethereum/pull/64 https://github.com/etclabscore/go-ethereum/pull/66
- [x] pantheon/besu https://github.com/ChainSafe/besu/pull/9 https://github.com/hyperledger/besu/pull/192
- [ ] mantis

**Comment by bobsummerwill** [comment]
@soc1c Mantis is not coming.
Best just to remove it from your lists (like this)

**Comment by bobsummerwill** [comment]
You could close this now - it's supported everywhere now.
